title: "MovingJu"
email: baramishe@gmail.com
timezone: Asia/Seoul
url: "http://movingju.github.io"
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/system/logo.png'
favicon: 'assets/images/system/favicon.ico'
author: MovingJu
paginate: 30
disqus: 'MovingJu'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: weekly
feed_update_frequency: 1

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed

ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: MovingJu
    display_name: MovingJu
    avatar: 'assets/images/system/MovingJu.png'
    email: baramishe@gmail.com
    web: https://github.com/MovingJu/movingju.github.io
    twitter: https://www.instagram.com/baramisjunior/
    description: "Artificial Intelligence student."
  MovingJu:
    name: MovingJu
    display_name: MovingJu
    avatar: 'assets/images/system/MovingJu.png'
    email: baramishe@gmail.com
    twitter: https://www.instagram.com/baramisjunior/
    web: https://github.com/MovingJu/movingju.github.io
    description: "Artificial Intelligence student."

# Social
social:
  instagram: https://www.instagram.com/baramisjunior/
  facebook: https://www.facebook.com/profile.php?id=100009087725229
  twitter: 

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
